include: package:very_good_analysis/analysis_options.5.0.0.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
#  errors:
#   Add this if json_serializable and Freezed shows this warning:
#    invalid_annotation_target: ignore

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
