name: civstart
description: App for helping Army veterans find jobs in the civilian market.
version: 1.0.1+28
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.4 <4.0.0"

dependencies:
  async: ^2.11.0
  bloc: ^8.1.2
  collection: ^1.17.1
  cupertino_icons: ^1.0.6
  firebase_analytics: ^10.4.5
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  freezed_annotation: 2.4.1
  get_it: ^7.6.4
  go_router: ^10.1.2
  html: ^0.15.4
  http: ^1.1.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  lottie: ^2.6.0
  meta: ^1.9.1
  sentry_flutter: ^7.9.0
  sentry_logging: ^7.9.0
  shared_preferences: ^2.2.1
  sliver_tools: ^0.2.12
  url_launcher: ^6.1.14
  visibility_detector: ^0.4.0+2

dev_dependencies:
  assets_gen: ^1.5.0
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  flutter_test:
    sdk: flutter
  freezed: 2.4.1
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  sentry_dart_plugin: ^1.6.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
  assets:
    - assets/animations/
    - assets/fonts/Poppins/OFL.txt
    - assets/images/

sentry:
  project: civstart-flutter
  org: miroma-project-factory
