name: my_wo
description: App for helping Army veterans find jobs in the civilian market.
version: 1.0.1+28
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.4 <4.0.0"

dependencies:
  async: ^2.11.0
  bloc: ^8.1.2
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  firebase_analytics: ^10.7.2
  firebase_core: ^2.24.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  freezed_annotation: 2.4.1
  get_it: ^7.6.4
  go_router: ^12.1.1
  html: ^0.15.4
  http: ^1.1.2
  json_annotation: ^4.8.1
  logging: ^1.2.0
  lottie: ^2.7.0
  meta: ^1.10.0
  shared_preferences: ^2.2.2
  sliver_tools: ^0.2.12
  url_launcher: ^6.2.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  assets_gen: ^1.5.0
  bloc_test: ^9.1.5
  build_runner: ^2.4.7
  build_verify: ^3.1.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mockito: ^5.4.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
  assets:
    - assets/animations/
    - assets/fonts/Poppins/OFL.txt
    - assets/images/

