// GENERATED CODE - DO NOT MODIFY BY HAND

// ignore_for_file: constant_identifier_names

// **************************************************************************
// Total assets: 51.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************
class Assets {
  static const String package = 'mywo';

  static const String assets_svg_back_svg = 'assets/svg/back.svg';
  static const String mywo$assets_svg_back_svg = 'packages/mywo/assets/svg/back.svg';
}
