// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 2.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'mywo';

  static const String assets_svg_back_svg = 'assets/svg/back.svg';
  static const String mywo$assets_svg_back_svg = 'packages/mywo/assets/svg/back.svg';

  static const String assets_svg_oval_header_svg = 'assets/svg/oval_header.svg';
  static const String mywo$assets_svg_oval_header_svg = 'packages/mywo/assets/svg/oval_header.svg';
}
