// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 98.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'civstart';

  static const String assets_animations_splash_screen_json =
      'assets/animations/splash_screen.json';
  static const String civstart$assets_animations_splash_screen_json =
      'packages/civstart/assets/animations/splash_screen.json';

  static const String assets_fonts_Poppins_OFL_txt =
      'assets/fonts/Poppins/OFL.txt';
  static const String civstart$assets_fonts_Poppins_OFL_txt =
      'packages/civstart/assets/fonts/Poppins/OFL.txt';

  static const String assets_images_adaptability_skill_png =
      'assets/images/adaptability_skill.png';
  static const String civstart$assets_images_adaptability_skill_png =
      'packages/civstart/assets/images/adaptability_skill.png';

  static const String assets_images_attention_to_detail_skill_png =
      'assets/images/attention_to_detail_skill.png';
  static const String civstart$assets_images_attention_to_detail_skill_png =
      'packages/civstart/assets/images/attention_to_detail_skill.png';

  static const String assets_images_communication_skill_png =
      'assets/images/communication_skill.png';
  static const String civstart$assets_images_communication_skill_png =
      'packages/civstart/assets/images/communication_skill.png';

  static const String assets_images_creativity_skill_png =
      'assets/images/creativity_skill.png';
  static const String civstart$assets_images_creativity_skill_png =
      'packages/civstart/assets/images/creativity_skill.png';

  static const String assets_images_gr_data_1_jpg =
      'assets/images/gr.data.1.jpg';
  static const String civstart$assets_images_gr_data_1_jpg =
      'packages/civstart/assets/images/gr.data.1.jpg';

  static const String assets_images_gr_interview_1_jpg =
      'assets/images/gr.interview.1.jpg';
  static const String civstart$assets_images_gr_interview_1_jpg =
      'packages/civstart/assets/images/gr.interview.1.jpg';

  static const String assets_images_gr_interview_2_jpg =
      'assets/images/gr.interview.2.jpg';
  static const String civstart$assets_images_gr_interview_2_jpg =
      'packages/civstart/assets/images/gr.interview.2.jpg';

  static const String assets_images_gr_interview_3_jpg =
      'assets/images/gr.interview.3.jpg';
  static const String civstart$assets_images_gr_interview_3_jpg =
      'packages/civstart/assets/images/gr.interview.3.jpg';

  static const String assets_images_gr_interview_4_jpg =
      'assets/images/gr.interview.4.jpg';
  static const String civstart$assets_images_gr_interview_4_jpg =
      'packages/civstart/assets/images/gr.interview.4.jpg';

  static const String assets_images_gr_interview_5_jpg =
      'assets/images/gr.interview.5.jpg';
  static const String civstart$assets_images_gr_interview_5_jpg =
      'packages/civstart/assets/images/gr.interview.5.jpg';

  static const String assets_images_gr_interview_6_jpg =
      'assets/images/gr.interview.6.jpg';
  static const String civstart$assets_images_gr_interview_6_jpg =
      'packages/civstart/assets/images/gr.interview.6.jpg';

  static const String assets_images_gr_job_1_jpg = 'assets/images/gr.job.1.jpg';
  static const String civstart$assets_images_gr_job_1_jpg =
      'packages/civstart/assets/images/gr.job.1.jpg';

  static const String assets_images_gr_job_2_jpg = 'assets/images/gr.job.2.jpg';
  static const String civstart$assets_images_gr_job_2_jpg =
      'packages/civstart/assets/images/gr.job.2.jpg';

  static const String assets_images_gr_job_3_jpg = 'assets/images/gr.job.3.jpg';
  static const String civstart$assets_images_gr_job_3_jpg =
      'packages/civstart/assets/images/gr.job.3.jpg';

  static const String assets_images_gr_job_4_jpg = 'assets/images/gr.job.4.jpg';
  static const String civstart$assets_images_gr_job_4_jpg =
      'packages/civstart/assets/images/gr.job.4.jpg';

  static const String assets_images_gr_job_5_jpg = 'assets/images/gr.job.5.jpg';
  static const String civstart$assets_images_gr_job_5_jpg =
      'packages/civstart/assets/images/gr.job.5.jpg';

  static const String assets_images_gr_job_6_jpg = 'assets/images/gr.job.6.jpg';
  static const String civstart$assets_images_gr_job_6_jpg =
      'packages/civstart/assets/images/gr.job.6.jpg';

  static const String assets_images_gr_job_7_jpg = 'assets/images/gr.job.7.jpg';
  static const String civstart$assets_images_gr_job_7_jpg =
      'packages/civstart/assets/images/gr.job.7.jpg';

  static const String assets_images_gr_job_8_jpg = 'assets/images/gr.job.8.jpg';
  static const String civstart$assets_images_gr_job_8_jpg =
      'packages/civstart/assets/images/gr.job.8.jpg';

  static const String assets_images_gr_linkedin_1_jpg =
      'assets/images/gr.linkedin.1.jpg';
  static const String civstart$assets_images_gr_linkedin_1_jpg =
      'packages/civstart/assets/images/gr.linkedin.1.jpg';

  static const String assets_images_gr_men_1_jpg = 'assets/images/gr.men.1.jpg';
  static const String civstart$assets_images_gr_men_1_jpg =
      'packages/civstart/assets/images/gr.men.1.jpg';

  static const String assets_images_gr_search_1_jpg =
      'assets/images/gr.search.1.jpg';
  static const String civstart$assets_images_gr_search_1_jpg =
      'packages/civstart/assets/images/gr.search.1.jpg';

  static const String assets_images_gr_search_10_jpg =
      'assets/images/gr.search.10.jpg';
  static const String civstart$assets_images_gr_search_10_jpg =
      'packages/civstart/assets/images/gr.search.10.jpg';

  static const String assets_images_gr_search_11_jpg =
      'assets/images/gr.search.11.jpg';
  static const String civstart$assets_images_gr_search_11_jpg =
      'packages/civstart/assets/images/gr.search.11.jpg';

  static const String assets_images_gr_search_12_jpg =
      'assets/images/gr.search.12.jpg';
  static const String civstart$assets_images_gr_search_12_jpg =
      'packages/civstart/assets/images/gr.search.12.jpg';

  static const String assets_images_gr_search_2_jpg =
      'assets/images/gr.search.2.jpg';
  static const String civstart$assets_images_gr_search_2_jpg =
      'packages/civstart/assets/images/gr.search.2.jpg';

  static const String assets_images_gr_search_3_jpg =
      'assets/images/gr.search.3.jpg';
  static const String civstart$assets_images_gr_search_3_jpg =
      'packages/civstart/assets/images/gr.search.3.jpg';

  static const String assets_images_gr_search_4_jpg =
      'assets/images/gr.search.4.jpg';
  static const String civstart$assets_images_gr_search_4_jpg =
      'packages/civstart/assets/images/gr.search.4.jpg';

  static const String assets_images_gr_search_5_jpg =
      'assets/images/gr.search.5.jpg';
  static const String civstart$assets_images_gr_search_5_jpg =
      'packages/civstart/assets/images/gr.search.5.jpg';

  static const String assets_images_gr_search_6_jpg =
      'assets/images/gr.search.6.jpg';
  static const String civstart$assets_images_gr_search_6_jpg =
      'packages/civstart/assets/images/gr.search.6.jpg';

  static const String assets_images_gr_search_7_jpg =
      'assets/images/gr.search.7.jpg';
  static const String civstart$assets_images_gr_search_7_jpg =
      'packages/civstart/assets/images/gr.search.7.jpg';

  static const String assets_images_gr_search_8_jpg =
      'assets/images/gr.search.8.jpg';
  static const String civstart$assets_images_gr_search_8_jpg =
      'packages/civstart/assets/images/gr.search.8.jpg';

  static const String assets_images_gr_search_9_jpg =
      'assets/images/gr.search.9.jpg';
  static const String civstart$assets_images_gr_search_9_jpg =
      'packages/civstart/assets/images/gr.search.9.jpg';

  static const String assets_images_gr_socials_1_jpg =
      'assets/images/gr.socials.1.jpg';
  static const String civstart$assets_images_gr_socials_1_jpg =
      'packages/civstart/assets/images/gr.socials.1.jpg';

  static const String assets_images_ico_check_svg =
      'assets/images/ico.check.svg';
  static const String civstart$assets_images_ico_check_svg =
      'packages/civstart/assets/images/ico.check.svg';

  static const String assets_images_ico_checklist_boxed_svg =
      'assets/images/ico.checklist.boxed.svg';
  static const String civstart$assets_images_ico_checklist_boxed_svg =
      'packages/civstart/assets/images/ico.checklist.boxed.svg';

  static const String assets_images_ico_checklist_checked_svg =
      'assets/images/ico.checklist.checked.svg';
  static const String civstart$assets_images_ico_checklist_checked_svg =
      'packages/civstart/assets/images/ico.checklist.checked.svg';

  static const String assets_images_ico_checklist_svg =
      'assets/images/ico.checklist.svg';
  static const String civstart$assets_images_ico_checklist_svg =
      'packages/civstart/assets/images/ico.checklist.svg';

  static const String assets_images_ico_checklist_unchecked_svg =
      'assets/images/ico.checklist.unchecked.svg';
  static const String civstart$assets_images_ico_checklist_unchecked_svg =
      'packages/civstart/assets/images/ico.checklist.unchecked.svg';

  static const String assets_images_ico_fact_svg = 'assets/images/ico.fact.svg';
  static const String civstart$assets_images_ico_fact_svg =
      'packages/civstart/assets/images/ico.fact.svg';

  static const String assets_images_ico_lightbulb_svg =
      'assets/images/ico.lightbulb.svg';
  static const String civstart$assets_images_ico_lightbulb_svg =
      'packages/civstart/assets/images/ico.lightbulb.svg';

  static const String assets_images_ico_logo_mark_svg =
      'assets/images/ico.logo.mark.svg';
  static const String civstart$assets_images_ico_logo_mark_svg =
      'packages/civstart/assets/images/ico.logo.mark.svg';

  static const String assets_images_ico_logo_svg = 'assets/images/ico.logo.svg';
  static const String civstart$assets_images_ico_logo_svg =
      'packages/civstart/assets/images/ico.logo.svg';

  static const String assets_images_ico_people_svg =
      'assets/images/ico.people.svg';
  static const String civstart$assets_images_ico_people_svg =
      'packages/civstart/assets/images/ico.people.svg';

  static const String assets_images_ico_person_svg =
      'assets/images/ico.person.svg';
  static const String civstart$assets_images_ico_person_svg =
      'packages/civstart/assets/images/ico.person.svg';

  static const String assets_images_ico_star_svg = 'assets/images/ico.star.svg';
  static const String civstart$assets_images_ico_star_svg =
      'packages/civstart/assets/images/ico.star.svg';

  static const String assets_images_ico_store_svg =
      'assets/images/ico.store.svg';
  static const String civstart$assets_images_ico_store_svg =
      'packages/civstart/assets/images/ico.store.svg';

  static const String assets_images_ico_tools_svg =
      'assets/images/ico.tools.svg';
  static const String civstart$assets_images_ico_tools_svg =
      'packages/civstart/assets/images/ico.tools.svg';

  static const String assets_images_ico_work_svg = 'assets/images/ico.work.svg';
  static const String civstart$assets_images_ico_work_svg =
      'packages/civstart/assets/images/ico.work.svg';

  static const String assets_images_ico_account_svg =
      'assets/images/ico_account.svg';
  static const String civstart$assets_images_ico_account_svg =
      'packages/civstart/assets/images/ico_account.svg';

  static const String assets_images_ico_after_svg =
      'assets/images/ico_after.svg';
  static const String civstart$assets_images_ico_after_svg =
      'packages/civstart/assets/images/ico_after.svg';

  static const String assets_images_ico_avoid_svg =
      'assets/images/ico_avoid.svg';
  static const String civstart$assets_images_ico_avoid_svg =
      'packages/civstart/assets/images/ico_avoid.svg';

  static const String assets_images_ico_beatthesystem_svg =
      'assets/images/ico_beatthesystem.svg';
  static const String civstart$assets_images_ico_beatthesystem_svg =
      'packages/civstart/assets/images/ico_beatthesystem.svg';

  static const String assets_images_ico_before_svg =
      'assets/images/ico_before.svg';
  static const String civstart$assets_images_ico_before_svg =
      'packages/civstart/assets/images/ico_before.svg';

  static const String assets_images_ico_brain_svg =
      'assets/images/ico_brain.svg';
  static const String civstart$assets_images_ico_brain_svg =
      'packages/civstart/assets/images/ico_brain.svg';

  static const String assets_images_ico_chat_svg = 'assets/images/ico_chat.svg';
  static const String civstart$assets_images_ico_chat_svg =
      'packages/civstart/assets/images/ico_chat.svg';

  static const String assets_images_ico_cross_svg =
      'assets/images/ico_cross.svg';
  static const String civstart$assets_images_ico_cross_svg =
      'packages/civstart/assets/images/ico_cross.svg';

  static const String assets_images_ico_do_svg = 'assets/images/ico_do.svg';
  static const String civstart$assets_images_ico_do_svg =
      'packages/civstart/assets/images/ico_do.svg';

  static const String assets_images_ico_during_svg =
      'assets/images/ico_during.svg';
  static const String civstart$assets_images_ico_during_svg =
      'packages/civstart/assets/images/ico_during.svg';

  static const String assets_images_ico_fav_svg = 'assets/images/ico_fav.svg';
  static const String civstart$assets_images_ico_fav_svg =
      'packages/civstart/assets/images/ico_fav.svg';

  static const String assets_images_ico_first_svg =
      'assets/images/ico_first.svg';
  static const String civstart$assets_images_ico_first_svg =
      'packages/civstart/assets/images/ico_first.svg';

  static const String assets_images_ico_info_svg = 'assets/images/ico_info.svg';
  static const String civstart$assets_images_ico_info_svg =
      'packages/civstart/assets/images/ico_info.svg';

  static const String assets_images_ico_interview_svg =
      'assets/images/ico_interview.svg';
  static const String civstart$assets_images_ico_interview_svg =
      'packages/civstart/assets/images/ico_interview.svg';

  static const String assets_images_ico_job_landscape_svg =
      'assets/images/ico_job_landscape.svg';
  static const String civstart$assets_images_ico_job_landscape_svg =
      'packages/civstart/assets/images/ico_job_landscape.svg';

  static const String assets_images_ico_jobsearch_svg =
      'assets/images/ico_jobsearch.svg';
  static const String civstart$assets_images_ico_jobsearch_svg =
      'packages/civstart/assets/images/ico_jobsearch.svg';

  static const String assets_images_ico_list_1_svg =
      'assets/images/ico_list-1.svg';
  static const String civstart$assets_images_ico_list_1_svg =
      'packages/civstart/assets/images/ico_list-1.svg';

  static const String assets_images_ico_list_2_svg =
      'assets/images/ico_list-2.svg';
  static const String civstart$assets_images_ico_list_2_svg =
      'packages/civstart/assets/images/ico_list-2.svg';

  static const String assets_images_ico_list_svg = 'assets/images/ico_list.svg';
  static const String civstart$assets_images_ico_list_svg =
      'packages/civstart/assets/images/ico_list.svg';

  static const String assets_images_ico_list_narrow_1_svg =
      'assets/images/ico_list_narrow-1.svg';
  static const String civstart$assets_images_ico_list_narrow_1_svg =
      'packages/civstart/assets/images/ico_list_narrow-1.svg';

  static const String assets_images_ico_list_narrow_svg =
      'assets/images/ico_list_narrow.svg';
  static const String civstart$assets_images_ico_list_narrow_svg =
      'packages/civstart/assets/images/ico_list_narrow.svg';

  static const String assets_images_ico_phone_svg =
      'assets/images/ico_phone.svg';
  static const String civstart$assets_images_ico_phone_svg =
      'packages/civstart/assets/images/ico_phone.svg';

  static const String assets_images_ico_privacy_svg =
      'assets/images/ico_privacy.svg';
  static const String civstart$assets_images_ico_privacy_svg =
      'packages/civstart/assets/images/ico_privacy.svg';

  static const String assets_images_ico_quiz_svg = 'assets/images/ico_quiz.svg';
  static const String civstart$assets_images_ico_quiz_svg =
      'packages/civstart/assets/images/ico_quiz.svg';

  static const String assets_images_ico_resources_svg =
      'assets/images/ico_resources.svg';
  static const String civstart$assets_images_ico_resources_svg =
      'packages/civstart/assets/images/ico_resources.svg';

  static const String assets_images_ico_school_svg =
      'assets/images/ico_school.svg';
  static const String civstart$assets_images_ico_school_svg =
      'packages/civstart/assets/images/ico_school.svg';

  static const String assets_images_ico_skill_svg =
      'assets/images/ico_skill.svg';
  static const String civstart$assets_images_ico_skill_svg =
      'packages/civstart/assets/images/ico_skill.svg';

  static const String assets_images_ico_skillhard_svg =
      'assets/images/ico_skillhard.svg';
  static const String civstart$assets_images_ico_skillhard_svg =
      'packages/civstart/assets/images/ico_skillhard.svg';

  static const String assets_images_ico_skillsoft_svg =
      'assets/images/ico_skillsoft.svg';
  static const String civstart$assets_images_ico_skillsoft_svg =
      'packages/civstart/assets/images/ico_skillsoft.svg';

  static const String assets_images_ico_support_svg =
      'assets/images/ico_support.svg';
  static const String civstart$assets_images_ico_support_svg =
      'packages/civstart/assets/images/ico_support.svg';

  static const String assets_images_ico_tips_svg = 'assets/images/ico_tips.svg';
  static const String civstart$assets_images_ico_tips_svg =
      'packages/civstart/assets/images/ico_tips.svg';

  static const String assets_images_ico_tnc_svg = 'assets/images/ico_tnc.svg';
  static const String civstart$assets_images_ico_tnc_svg =
      'packages/civstart/assets/images/ico_tnc.svg';

  static const String assets_images_ico_warning_svg =
      'assets/images/ico_warning.svg';
  static const String civstart$assets_images_ico_warning_svg =
      'packages/civstart/assets/images/ico_warning.svg';

  static const String assets_images_interpersonal_skill_png =
      'assets/images/interpersonal_skill.png';
  static const String civstart$assets_images_interpersonal_skill_png =
      'packages/civstart/assets/images/interpersonal_skill.png';

  static const String assets_images_job_search_header_png =
      'assets/images/job_search_header.png';
  static const String civstart$assets_images_job_search_header_png =
      'packages/civstart/assets/images/job_search_header.png';

  static const String assets_images_leadership_skill_png =
      'assets/images/leadership_skill.png';
  static const String civstart$assets_images_leadership_skill_png =
      'packages/civstart/assets/images/leadership_skill.png';

  static const String assets_images_lg_dfwa_png = 'assets/images/lg.dfwa.png';
  static const String civstart$assets_images_lg_dfwa_png =
      'packages/civstart/assets/images/lg.dfwa.png';

  static const String assets_images_man_typing_jpg =
      'assets/images/man_typing.jpg';
  static const String civstart$assets_images_man_typing_jpg =
      'packages/civstart/assets/images/man_typing.jpg';

  static const String assets_images_patient_list_outlined_svg =
      'assets/images/patient_list_outlined.svg';
  static const String civstart$assets_images_patient_list_outlined_svg =
      'packages/civstart/assets/images/patient_list_outlined.svg';

  static const String assets_images_problem_solving_skill_png =
      'assets/images/problem_solving_skill.png';
  static const String civstart$assets_images_problem_solving_skill_png =
      'packages/civstart/assets/images/problem_solving_skill.png';

  static const String assets_images_resources_header_png =
      'assets/images/resources_header.png';
  static const String civstart$assets_images_resources_header_png =
      'packages/civstart/assets/images/resources_header.png';

  static const String assets_images_resume_jpg = 'assets/images/resume.jpg';
  static const String civstart$assets_images_resume_jpg =
      'packages/civstart/assets/images/resume.jpg';

  static const String assets_images_skill_header_png =
      'assets/images/skill_header.png';
  static const String civstart$assets_images_skill_header_png =
      'packages/civstart/assets/images/skill_header.png';

  static const String assets_images_teamwork_skill_png =
      'assets/images/teamwork_skill.png';
  static const String civstart$assets_images_teamwork_skill_png =
      'packages/civstart/assets/images/teamwork_skill.png';

  static const String assets_images_time_management_skill_png =
      'assets/images/time_management_skill.png';
  static const String civstart$assets_images_time_management_skill_png =
      'packages/civstart/assets/images/time_management_skill.png';

  static const String assets_images_tips_and_tricks_header_png =
      'assets/images/tips_and_tricks_header.png';
  static const String civstart$assets_images_tips_and_tricks_header_png =
      'packages/civstart/assets/images/tips_and_tricks_header.png';

  static const String assets_images_work_ethic_skill_png =
      'assets/images/work_ethic_skill.png';
  static const String civstart$assets_images_work_ethic_skill_png =
      'packages/civstart/assets/images/work_ethic_skill.png';
}
